---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: webapp-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-operator
  labels:
    control-plane: webapp-operator
spec:
  selector:
    matchLabels:
      control-plane: webapp-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: webapp-operator
    spec:
      serviceAccountName: webapp-operator
      containers:
        - name: manager
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          args:
            - "--enable-leader-election"
            - "--leader-election-id=webapp-operator"
          env:
            - name: ANSIBLE_GATHERING
              value: explicit            
            - name: OPERATOR_NAME
              value: "webapp-operator"
            - name: RELATED_IMAGE_FRONTEND
              value: vaibhavkhabani/flask-plagirism-api:v1              
      terminationGracePeriodSeconds: 10
