# permissions for end users to view webapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webapp-viewer-role
rules:
- apiGroups:
  - example.com
  resources:
  - webapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.com
  resources:
  - webapps/status
  verbs:
  - get
